### ISSUE TITLE
unconventional logic (question)

### ISSUE THREAD

**Issue by lwhiteley** [DamonOehlman/wildcard#10]
your example
```js
var wildcard = require('wildcard');
var testdata = [
  'a.b.c',
  'a.b',
  'a',
  'a.b.d'
];
 
console.log(wildcard('a.b.*', testdata));
// --> ['a.b.c', 'a.b', 'a.b.d'] 
```

Why does the wildcard `a.b.*` map to `a.b` when the extra `.` (dot) after the `b` in the wildcard rules it out?

Correct me if I'm wrong but usually `a.b.*` means all strings that start with `a.b.`

Is there a reason why this library is doing otherwise?

Thanks

**Comment by lwhiteley** [comment]
found a library that does what i need. so closing

**Comment by DamonOehlman** [comment]
I agree with you - what library did you find that did what you needed?  I should probably include a link to it in the readme.

Not sure why I originally made `a.b.*` match `a.b` - I know from memory I tried to make it behave as similarly to [`eve`](https://github.com/adobe-webplatform/eve) but I doubt it would do that so it seems like a bug to me.

**Comment by lwhiteley** [comment]
https://www.npmjs.com/package/wildcard2

On Mon, 4 Apr 2016 at 19:13 Damon Oehlman <notifications@github.com> wrote:

> I agree with you - what library did you find that did what you needed? I
> should probably include a link to it in the readme.
>
> Not sure why I originally made a.b.* match a.b - I know from memory I
> tried to make it behave as similarly to eve
> <https://github.com/adobe-webplatform/eve> but I doubt it would do that
> so it seems like a bug to me.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/DamonOehlman/wildcard/issues/10#issuecomment-205536780>
>
-- 
_______________
Regards
Layton Whiteley

**Comment by DamonOehlman** [comment]
Awesome - thanks :)
